- name: load maven'
  ansible.builtin.import_role:
    name: common
    tasks_from: maven



source common.sh
component=shipping

mysql_root_password=$1
if [ -z "$mysql_root_password" ]; then
 echo "mysql password is missing"
 exit 1
fi 
maven