- name: disable mysql default version
  ansible.builtin.shell: yum module disable mysql -y 

- name: copy mysql repo files
  ansible.builtin.copy:
     src: mysql.repo
     dest: /etc/yum.repos.d/mysql.repo 
 
- name: install mysql server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: restart mysql server
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: setup root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
    