- name: install maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: app presetup
  ansile.builtin.import_tasks:
    file: app_presetup.yml

- name: downloading maven dependencies
  ansible.builtin.shell: mvn clean package ;  mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app

- name: mysql chema setup
  ansile.builtin.import_tasks:
    file: mysql_schema_setup.yml

- name: sysemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
