- name: Install mysql client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: load schema
  ansible.builtin.shell: mysql --host mysql-dev.keedev.store </app/schema/{{ component }}.sql
       
      